### ISSUE TITLE
TimeSeries Search

### ISSUE THREAD

**Issue by njss** [ChronixDB/chronix.examples#14]
Is there any (or do you plan to develop) any search queries by selection and return the best-found matches that correspond to one or more selections?

**Comment by FlorianLautenschlager** [comment]
Hi, sorry for the delay - if have unwatched the project... damn :worried: 

Just to be sure: You want to find a time series based on a selection (e.g. 3 hours) of a other time series? Or do you want to find a time series based on its attributes (call it labels or metadata).

**Comment by njss** [comment]
:) I would say both! But I asked the question because I was thinking in using this system for an evaluation using an eye-tracker, and I would like to select a piece of one time series and look for similar matches in all time series stored.

**Comment by FlorianLautenschlager** [comment]
Actually you can do both. Perhaps a good start is [sax](http://www.cs.ucr.edu/~eamonn/SAX.htm). You can pre-calculate the symbolic representation of a time series and store it as attribute on each chunk.
With this you can use the features of Apache Solr.

A time series `[(1,5),(2,2),(3,7),(4,5)]` is represented with sax as `CADC`. Simply store `CADC` as an attribute: [sax:CADC,start=1,end=4, data=<binary>,...]. With this you can search for pattern like `sax: *AD*` which finds every time series having *AD* in its symbolic representation. You an do this also on the fly with the sax function which needs more memory.

The other thing you can try is FastDTW. Chronix provides such a function: https://github.com/ChronixDB/chronix.server

**Comment by njss** [comment]
Thank you so much for your replies. Are these search functionalities also present in your javafx ui example?
