### ISSUE TITLE
Can not query timeseries data using example given under  chronix-server-integration - Metric timeseries

### ISSUE THREAD

**Issue by Niranjs** [ChronixDB/chronix.examples#16]
Hi,
I tried example given under "chronix-server-integration" ChronixClientExampleWithMetricTimeSeries.java
I wrote the follow program to store time series.

        //An connection to Solr
        HttpSolrClient.Builder builder = new HttpSolrClient.Builder();
        builder.withBaseSolrUrl("http://localhost:8983/solr/chronix/");
        HttpSolrClient httpSolrClient = builder.build();

        //Create a Chronix Client with a metric time series and the Chronix Solr Storage
        ChronixClient<MetricTimeSeries,SolrClient,SolrQuery> chronix = 
                                                  new ChronixClient<>(new MetricTimeSeriesConverter(),
                                                  new ChronixSolrStorage<>(nrOfDocsPerBatch,groupBy,reduce));

        //Store data
        MetricTimeSeries ts = createMetricTS("load", "metric");
        List<MetricTimeSeries> tsList = new ArrayList<>();
        tsList.add(ts);
        boolean bool = chronix.add(tsList, httpSolrClient);
        System.out.println("Metric added: " + bool);  //this prints true. That means it stores properly.

    private static MetricTimeSeries createMetricTS(String name, String type) {
        //Build a metric time series with three points
        MetricTimeSeries series = new MetricTimeSeries.Builder(name, type)
              .attribute("host", "lapp32")
//              .attribute("process", "chronix")
              .point(Instant.now().toEpochMilli(), 527)
              .point(Instant.now().plusSeconds(60).toEpochMilli(), 683)
              .point(Instant.now().plusSeconds(30).toEpochMilli(), 528)
//              .attribute("max", 683)
              .build();
     }

But when tried to query using example given returns nothing. Also from solr dashborad I got zero result.

Can any one suggest what am I doing wrongly.

**Comment by FlorianLautenschlager** [comment]
Hi,

sorry for the late response. I am on vacation an will dig into this on monday, when i am back and have access to my laptop. 

Perhaps you missed to call `commit` on the `HttpSolrClient`?

**Comment by Niranjs** [comment]
I did not commit after storing the data (metrics). I added the following to achieved it.

UpdateResponse updateResponse = httpSolrClient.commit(true, true);
