### ISSUE TITLE
Chronix Example UI with openJDK

### ISSUE THREAD

**Issue by FlorianLautenschlager** [ChronixDB/chronix.examples#7]
If one tries to execute Chronix UI with openJDK the main class is not found.

**Comment by DanielJoyce** [comment]
This hasn't been fixed? Still getting it with latest example in quickstart. 

Could not find or load main class de.qaware.chronix.examples.exploration.ui.MainRunner

Also, if this bug is over a year old, it opens serious questions about the viability of the project.

**Comment by FlorianLautenschlager** [comment]
No not yet. It was reported by myself and it seems that it not really important. There are other things on my plate. But now it is and I will fix this evening. 

Thanks for your comment.

**Comment by DanielJoyce** [comment]
Okay, problem is OpenJDK does not ship with a build of Javafx on linux, so on linux you need to install oracle jdk

http://sourcedigit.com/22256-how-to-install-oracle-java-on-ubuntu-17-04/

**Comment by FlorianLautenschlager** [comment]
An alternative is to install openjfx. I will check if it works.
